name: Create Release

on:
  workflow_run:
    workflows: ["Debug"]
    types:
      - completed

jobs:
  create_release:
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Automatic Release
            Workflow Run ID: ${{ github.event.workflow_run.id }}
            [See artifacts](${{ github.event.workflow_run.artifacts_url }})
          draft: false
          prerelease: false

      - name: Attach Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: path/to/artifact
          asset_name: my-artifact
          asset_content_type: application/zip
